%YAML 1.2
---
name: BenjaminVega10-v1
gpu: 0

dataset:
  input_train: 'data/processed/1100/*.npz'
  input_test: 'data/processed/1100/*.npz'

training:
  precision: 'float32'          # CPU doesn't benefit from 'half'
  batch_size: 64                # Smaller batch size to fit RAM
  num_batch_splits: 1
  test_steps: 500
  train_avg_report_steps: 50
  total_steps: 200            # Conservative step count; increase if training is stable
  checkpoint_steps: 1000
  shuffle_size: 50000
  lr_values:
    - 0.001
    - 0.0005
    - 0.0001
  lr_boundaries:
    - 3000
    - 6000
  policy_loss_weight: 1.0
  value_loss_weight: 1.0
  learning_rate: 0.001
  num_training_steps: 200

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
  blocks: 6
  value_head_hidden: 128
...
